---
kind: Service
metadata:
  name: example-nodeport-service
  # namespace: kube-system
spec:
  selector:
    app: select_me
  ports:
    - protocol: TCP
      port: 80
      name: web
      nodePort: 30080
    - protocol: TCP
      port: 8080
      name: admin
      nodePort: 30808
  type: NodePort
